language: node_js
node_js: 5

branches:
    only: master

install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install grunt-cli -g
    - npm install

script: grunt travis -v

notifications:
    email: geloen.eric@gmail.com
