language: node_js

install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install grunt-cli -g
    - npm install
    - node_modules/protractor/bin/webdriver-manager update

script: grunt travis

notifications:
    email: geloen.eric@gmail.com
